### ISSUE TITLE
Dialplan Prefix Ignored in Survey Call Transfer

### ISSUE THREAD

**Issue by nblasgen** [newfies-dialer/newfies-dialer#36]
I have a prefix defined in my Dialer Gateway (Dialer Gateway -> Advanced -> Add Prefix).  The prefix is being ignored when I ask the Survey module to do a Call Transfer (Survey -> Call Transfer -> Phone Number / SIP URI).

Expected result:
If the transfer isn't to a valid SIP URI, then it should send the call to the proper voip gateway (which it's doing) and append the defined prefix (which it's not doing).

**Comment by areski** [comment]
This has been fixed!
