### ISSUE TITLE
Campaing calls dropping after pickup

### ISSUE THREAD

**Issue by Daniel-Nascimento** [newfies-dialer/newfies-dialer#39]
I don't know what is happening, but all calls from a camping is droping after pick'em up the phones (mobile included).

There's some error logs in Sofia:

2014-02-18 15:04:16.657718 [ERR] mod_lua.cpp:199 /usr/share/newfies-lua/libs/fsm_callflow.lua:18: module 'loop.simple' not found:
	no field package.preload['loop.simple']
	no file '/usr/local/share/lua/5.2/loop/simple.lua'
	no file '/usr/local/share/lua/5.2/loop/simple/init.lua'
	no file '/usr/local/lib/lua/5.2/loop/simple.lua'
	no file '/usr/local/lib/lua/5.2/loop/simple/init.lua'
	no file './loop/simple.lua'
	no file '/usr/share/newfies-lua/loop/simple.lua'
	no file '/usr/share/newfies-lua/libs/loop/simple.lua'
	no file '/usr/share/newfies-lua/loop/simple.lua'
	no file '/usr/share/newfies-lua/libs/loop/simple.lua'
	no file '/usr/local/lib/lua/5.2/loop/simple.so'
	no file '/usr/local/lib/lua/5.2/loadall.so'
	no file './loop/simple.so'
	no file '/usr/local/lib/lua/5.2/loop.so'
	no file '/usr/local/lib/lua/5.2/loadall.so'
	no file './loop.so'
stack traceback:
	[C]: in function 'require'
	/usr/share/newfies-lua/libs/fsm_callflow.lua:18: in main chunk
	[C]: in function 'require'
	/usr/share/newfies-lua/newfies.lua:18: in main chunk

While doing the call - watching this dump -it is right in this moment that my call rang in my mobile and after pick up - this error above pops-up.

Maybe is related - should I use a specific version of LUA libs?

**Comment by areski** [comment]
that was a problem of dependencies, anyway in the latest versions we never had this problem reported.
