### ISSUE TITLE
Frontend GUI issue in newfies dialer

### ISSUE THREAD

**Issue by niravtrivedi** [newfies-dialer/newfies-dialer#40]
Hi 
I have been install step by step newfies-dialer it install success but getting gui problem in frontside find error as bellow
[13/Mar/2014 15:34:19] "GET /static/bootstrap/dist/js/bootstrap.js HTTP/1.1" 404 1700
+ some of css are 404 

Also include "from django.contrib.staticfiles.urls import staticfiles_urlpatterns".
Also copied all necessary files to static.

Please help me thank you in advance.

**Comment by areski** [comment]
The last version works perfectly, reopen if you still have an issue
