### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by tomcsanyid** [newfies-dialer/newfies-dialer#41]
I got this error while trying to install newfies-dialer using the installer script (on a brand new installed Debian 7 system):

ImportError: Could not import settings 'newfies_dialer.settings' (Is it on sys.path? Is there an import error in the settings file?): cannot import name OrderedDict

After some hours of debugging what I found is that you are using the github version of kombu in the requirements.txt and that version isn't functional for some reason. Swapping it with the kombu version pip installs (e.g.: pip install kombu) the error went away.
I would strongly suggest to remove the github version of kombu from the requirements.txt.

**Comment by tarikgwa** [comment]
I have did a fresh instalaltion of newfies version 2.16.3  from your github repository "install.sh", but when i try to accessed to the x.x.x.x:8008 "Customer Portal  or Administrator Panel" i got the "404 Not Found".

**Comment by bharatahuja07** [comment]
I am too facing the same issue. 404 not found. Installation was successful even ngnix is also running properly. But I think document root is not point at proper file/folder. Please help me to resolve this issue.

**Comment by kavikomi** [comment]
same probleme 404 ???

**Comment by vaheed** [comment]
any news ? , i install on Debian 8 with script and same problem !!!
