### ISSUE TITLE
install stuck on luarocks

### ISSUE THREAD

**Issue by YAmikep** [newfies-dialer/newfies-dialer#43]
Hi,

The install script is stuck on the following:

```
--2014-07-30 03:29:32--  (try: 3)  http://luarocks.org/releases/luarocks-2.1.2.tar.gz
Connecting to luarocks.org (luarocks.org)|184.95.38.38|:80... connected.
HTTP request sent, awaiting response...
```

I will retry later.

Anyway, I was wondering how to test the whole installation and FreeSwitch when everything is installed?

Thank you

**Comment by areski** [comment]
our install script use rocks from moonscript if luarocks is down::

    #Check if Luarocks
    LUAROCKS_UP=$(ping -c 2 luarocks.org 2>&1 | grep -c "100%")
    case $LUAROCKS_UP in
        1)
            echo "Luarocks is DOWN!"
            echo ""
            echo "We will set a mirror"
            mkdir ~/.luarocks
            rm ~/.luarocks/config.lua
            # echo '   rocks_servers={ "http://luarocks.giga.puc-rio.br/" }' >> ~/.luarocks/config.lua
            echo '   rocks_servers={ "http://rocks.moonscript.org/manifests/luarocks/" }' >> ~/.luarocks/config.lua
        ;;
    esac
