### ISSUE TITLE
404 not found 

### ISSUE THREAD

**Issue by serhatalpaslan** [newfies-dialer/newfies-dialer#44]
404 Not Found ... fresh install version ""release/v2.13.13""
nginx/1.2.1

log file ....

88.247.36.122 - - [23/Sep/2014:12:41:55 +0300] "GET / HTTP/1.1" 200 2167 "-" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:32.0) Gecko/20100101 Firefox/32.0"
88.247.36.122 - - [23/Sep/2014:12:41:55 +0300] "GET /images/favicon.png HTTP/1.1" 200 944 "-" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:32.0) Gecko/20100101 Firefox/32.0"
88.247.36.122 - - [23/Sep/2014:12:41:55 +0300] "GET /bootstrap/css/bootstrap.min.css HTTP/1.1" 200 99548 "http://212.175.17.228/" "Mozilla/5.0 (Windows NT 6.3; WOW64; $
88.247.36.122 - - [23/Sep/2014:12:41:55 +0300] "GET /bootstrap/js/bootstrap.min.js HTTP/1.1" 200 27822 "http://212.175.17.228/" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv$
88.247.36.122 - - [23/Sep/2014:12:41:55 +0300] "GET /images/newfies-dialer.png HTTP/1.1" 200 26301 "http://212.175.17.228/" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:32.$
88.247.36.122 - - [23/Sep/2014:12:41:56 +0300] "GET /jquery/jquery.min.js HTTP/1.1" 200 83606 "http://212.175.17.228/" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:32.0) Ge$
88.247.36.122 - - [23/Sep/2014:12:42:01 +0300] "-" 400 0 "-" "-"
88.247.36.122 - - [23/Sep/2014:12:42:01 +0300] "-" 400 0 "-" "-"
88.247.36.122 - - [23/Sep/2014:12:43:38 +0300] "GET / HTTP/1.1" 200 2167 "-" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:32.0) Gecko/20100101 Firefox/32.0"
88.247.36.122 - - [23/Sep/2014:12:43:38 +0300] "GET /images/favicon.png HTTP/1.1" 200 944 "-" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:32.0) Gecko/20100101 Firefox/32.0"
88.247.36.122 - - [23/Sep/2014:12:43:38 +0300] "GET /bootstrap/css/bootstrap.min.css HTTP/1.1" 200 99548 "http://212.175.17.228/" "Mozilla/5.0 (Windows NT 6.3; WOW64; $
88.247.36.122 - - [23/Sep/2014:12:43:38 +0300] "GET /images/newfies-dialer.png HTTP/1.1" 200 26301 "http://212.175.17.228/" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:32.$
88.247.36.122 - - [23/Sep/2014:12:43:38 +0300] "GET /bootstrap/js/bootstrap.min.js HTTP/1.1" 200 27822 "http://212.175.17.228/" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv$
88.247.36.122 - - [23/Sep/2014:12:43:38 +0300] "GET /jquery/jquery.min.js HTTP/1.1" 200 83606 "http://212.175.17.228/" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:32.0) Ge$
88.247.36.122 - - [23/Sep/2014:12:43:44 +0300] "-" 400 0 "-" "-"
88.247.36.122 - - [23/Sep/2014:12:43:44 +0300] "-" 400 0 "-" "-"
88.247.36.122 - - [23/Sep/2014:12:49:21 +0300] "GET /images/favicon.png HTTP/1.1" 200 944 "-" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:32.0) Gecko/20100101 Firefox/32.0"
88.247.36.122 - - [23/Sep/2014:12:49:27 +0300] "-" 400 0 "-" "-"
88.247.36.122 - - [23/Sep/2014:12:53:29 +0300] "GET / HTTP/1.1" 200 2167 "-" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:32.0) Gecko/20100101 Firefox/32.0"
88.247.36.122 - - [23/Sep/2014:12:53:29 +0300] "GET /images/favicon.png HTTP/1.1" 200 944 "-" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:32.0) Gecko/20100101 Firefox/32.0"
88.247.36.122 - - [23/Sep/2014:12:53:29 +0300] "GET /bootstrap/css/bootstrap.min.css HTTP/1.1" 200 99548 "http://212.175.17.228/" "Mozilla/5.0 (Windows NT 6.3; WOW64; $
88.247.36.122 - - [23/Sep/2014:12:53:29 +0300] "GET /bootstrap/js/bootstrap.min.js HTTP/1.1" 200 27822 "http://212.175.17.228/" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv$
88.247.36.122 - - [23/Sep/2014:12:53:29 +0300] "GET /images/newfies-dialer.png HTTP/1.1" 200 26301 "http://212.175.17.228/" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:32.$
88.247.36.122 - - [23/Sep/2014:12:53:29 +0300] "GET /jquery/jquery.min.js HTTP/1.1" 200 83606 "http://212.175.17.228/" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:32.0) Ge$
88.247.36.122 - - [23/Sep/2014:12:53:35 +0300] "-" 400 0 "-" "-"
88.247.36.122 - - [23/Sep/2014:12:53:35 +0300] "-" 400 0 "-" "-"

**Comment by areski** [comment]
last version should work perfectly

**Comment by jedi77** [comment]
can you please post link to last version and instructions how to install it? I used this link to install

wget --no-check-certificate http://bit.ly/newfies-dialer-installer -O install-all.sh

bash install-all.sh

Thanks.

**Comment by nawaz123** [comment]
cannot install newfies fully. give following error while accessing local address x.x.x.x:8008 
 404 not found.   nginx/1.6.2

**Comment by itsniteshrana** [comment]
I have tried many times to install the newfies dialer but after every installtion i got the 404 Not Found
nginx/1.6.2  and its not asking to create the username and password option kindly help for the issue

**Comment by itsniteshrana** [comment]
> last version should work perfectly
can you please share the last version link as new version link is not working at all after installation getting error 404 Not Found
