### ISSUE TITLE
rest-api documentation incorrect

### ISSUE THREAD

**Issue by MarcNealer** [newfies-dialer/newfies-dialer#47]
Hi

the following is incorrect

http://docs.newfies-dialer.org/en/latest/api-doc/sms_gateway_serializers.html

It refers to accessing the dial gateway not the SMS gateway. I am assuming its almost the same, but the URL will definitely be different. I have a customer waiting on a script for your system and this documentation.

thanks

Marc Nealer

**Comment by areski** [comment]
Newfies-Dialer open source development was discontinued in 2015, but Newfies-Dialer continues to be developed as a commercial closed source product. See https://www.newfies-dialer.org

Newfies-Dialer is an auto-dialer supporting multi-tenancy and billing. You use your own VoIP carrier so there are potentially huge savings to be made when using Newfies-Dialer compared to competing products who insist on using their VoIP termination.

In recent years, there are countless improvements in terms of features, benefits and capacity of Newfies-Dialer. There is a list of changes at https://www.newfies-dialer.org/newfies-dialer-sms-voice-broadcasting-software-changelog/
