### ISSUE TITLE
How integrate nexmo with newfies?

### ISSUE THREAD

**Issue by johnfelipe** [newfies-dialer/newfies-dialer#52]

**Comment by areski** [comment]
if you need custom development please contact newfies-dialer@star2billing.com
otherwise please open an issue for related issue to newfies-dialer or to provide code changes via PR

**Comment by johnfelipe** [comment]
I can configure any provider that have http api?

**Comment by areski** [comment]
no, please see the list of supported gateway in the documentation

**Comment by johnfelipe** [comment]
but voice with nexmo work, please share me link for learn all

**Comment by areski** [comment]
feel free to provide a pull request to change the documentation, if you make it work we will be happy to add it in the doc

**Comment by johnfelipe** [comment]
any documentation for try add that integration?
