### ISSUE TITLE
script not working

### ISSUE THREAD

**Issue by vaheed** [newfies-dialer/newfies-dialer#57]
hello, after install with script on debian 8 , not work, 
i found proxy_pass http://127.0.0.1:8123/
and after 

root@autodialer:/usr/share/newfies# netstat -nlp | grep -i 8
tcp        0      0 0.0.0.0:8008            0.0.0.0:*               LISTEN      17104/nginx -g daem
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      17104/nginx -g daem
tcp        0      0 0.0.0.0:8081            0.0.0.0:*               LISTEN      17474/freeswitch
tcp        0      0 0.0.0.0:8082            0.0.0.0:*               LISTEN      17474/freeswitch
tcp        0      0 0.0.0.0:55731           0.0.0.0:*               LISTEN      485/rpc.statd
tcp        0      0 127.0.0.1:8021          0.0.0.0:*               LISTEN      17474/freeswitch
tcp        0      0 10.10.10.253:5080       0.0.0.0:*               LISTEN      17474/freeswitch
tcp6       0      0 :::48787                :::*                    LISTEN      485/rpc.statd
tcp6       0      0 ::1:5080                :::*                    LISTEN      17474/freeswitch
udp        0      0 0.0.0.0:57777           0.0.0.0:*                           485/rpc.statd
udp        0      0 127.0.0.1:661           0.0.0.0:*                           485/rpc.statd
udp        0      0 10.10.10.253:5080       0.0.0.0:*                           17474/freeswitch
udp6       0      0 ::1:5080                :::*                                17474/freeswitch
udp6       0      0 :::37233                :::*                                485/rpc.statd
unix  2      [ ACC ]     SEQPACKET  LISTENING     10078    1/init              /run/udev/control

**Comment by areski** [comment]
Newfies-Dialer open source development was discontinued in 2015, but Newfies-Dialer continues to be developed as a commercial closed source product. See https://www.newfies-dialer.org

Newfies-Dialer is an auto-dialer supporting multi-tenancy and billing. You use your own VoIP carrier so there are potentially huge savings to be made when using Newfies-Dialer compared to competing products who insist on using their VoIP termination.

In recent years, there are countless improvements in terms of features, benefits and capacity of Newfies-Dialer. There is a list of changes at https://www.newfies-dialer.org/newfies-dialer-sms-voice-broadcasting-software-changelog/
